module.exports = {
  routes: {
    root: '/',
    index: '/',
    about: 'about',
    post: 'posts',
    category: 'categories',
    tag: 'tags',
    populars: 'populars',
    pickups: 'pickups'
  },
  search: {
    index: 'my-blog-posts',
  },
  meta: {
    author: 'version1',
    siteUrl: 'https://ver-1-0.net',
    logo: 'https://statics.ver-1-0.xyz/uploads/others/logo.png',
    hostname: 'ver-1-0.net',
    title: 'So Far, So Tech',
    description:
      'フリーランスエンジニアのブログです。フリーランス、プログラミング、旅行について「ブログ書け、コード書け」というテーマでやらせてもらってます。',
    sitemap: '/sitemap.xml',
    trackingId: 'UA-71833989-5',
    images: {
      url: 'https://statics.ver-1-0.xyz/uploads'
    },
    postRoot: '/Users/admin/Projects/Private/blog/src/pages/posts'
  },
  constants: {
    per: 9,
    categories: [
      'column',
      'cryptocurrency-blockchain',
      'design',
      'engineering',
      'for-beginner',
      'freelance',
      'rails',
      'react',
      'travel'
    ],
    tags: [
      'ansible',
      'activerecord',
      'book',
      'bitcoin',
      'blade',
      'blockchain',
      'build-env',
      'cakephp',
      'career',
      'canada',
      'command',
      'commentary',
      'coolors',
      'cryptocurrency',
      'ci',
      'circleci',
      'css',
      'design',
      'design-pattern',
      'docker',
      'english',
      'exposed',
      'editor',
      'essay',
      'ethereum',
      'egg-cutter',
      'freelance',
      'frontend',
      'flyway',
      'ga',
      'gatsby',
      'gadget',
      'git',
      'go',
      'hello-world',
      'inkdrop',
      'javascript',
      'jest',
      'kotlin',
      'khttp',
      'laravel',
      'learning',
      'lifehack',
      'lubuntu',
      'lodash',
      'mac',
      'marketing',
      'migration',
      'mysql',
      'native',
      'netlify',
      'nginx',
      'nodejs',
      'oculus',
      'opinion',
      'oop',
      'phantomjs',
      'php',
      'phpunit',
      'plugin',
      'product',
      'postgress',
      'pomodoro',
      'react',
      'redux',
      'react-native',
      'react-navigation',
      'review',
      'rails',
      'ruby',
      'spa',
      'springboot',
      'slack',
      'smaccs',
      'snakegame',
      'serverside',
      'test',
      'travel',
      'vagrant',
      'vue',
      'vuex',
      'web-structure',
      'webpack',
      'wordpress',
      'work'
    ],
    selectors: [
      '.js-ga-click-levatech-freelance',
      '.js-ga-click-it-propartners',
      '.js-ga-click-potepan-freelance',
      '.js-ga-click-book-marketing-sence',
      '.js-ga-click-sns-twitter',
      '.js-ga-click-sns-facebook',
      '.js-ga-click-sns-google-plus',
      '.js-ga-click-sns-reddit',
      '.js-ga-click-sns-pocket',
      '.js-ga-click-sns-hatebu',
      '.js-ga-click-amazon',
      '.js-ga-click-airtori',
      '.js-ga-click-global-wifi',
      '.adsense'
    ],
    pickup: [
      '/2020/01/01/review-2020',
      '/2019/09/24/get-start-circle-ci-confg-2-1',
      '/2019/05/13/gin-gorm-gqlgen-crud'
    ],
    pages: ['about']
  }
}
